# name: payment-service
# version: v1.0.0
# # "latest" hata kar koi version number dalo
# image: ghcr.io/my-org/payments:v1.0.2 
# replicas: 3
# security_level: high


# name: "payment-service"
# version: "v1.0.0"
# image: "nginx:latest"  # Isse change karo
# replicas: 1
# security_level: "high"


name: "payment-service"
version: "v1.0.0"
image: "nginx:1.25.3"  # <--- Specifying a version to pass policy check
replicas: 1
security_level: "high"