name: "payment-service"
version: "1.0.0"
image: "nginx:1.25.3"
replicas: 1
security_level: "high"
# Naya Section jo humne Phase 2 mein add kiya:
resources:
  cpu: 0.2        # Matlab 20% of a single CPU core
  memory: 64      # Matlab sirf 64MB RAM limit